# Generated by Django 2.1.7 on 2019-03-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190314_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
