# Generated by Django 2.1.7 on 2019-03-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('employees', '0003_auto_20190314_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Position',
            },
        ),
        migrations.RemoveField(
            model_name='department',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='slug',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_head',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='parentId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Position'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='Employees',
        ),
    ]
