# Generated by Django 2.1.7 on 2019-03-16 14:16

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('employees', '0005_auto_20190316_1610'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='Employees',
        ),
        migrations.AlterModelTable(
            name='position',
            table='Position',
        ),
    ]
